# config.yaml
slides:
  # --- Master library of reusable slides ---
  - id: kitchen_before
    file: "kitchen_before.JPG"
    #title: "Kitchen before"
    effect: kenburns-zoom-in
    duration: 10

  - id: kitchen_during
    file: "kitchen_during/*.JPG"
    #title: "Kitchen during ..."
    effect: cut
    duration: 3

  - id: kitchen_after
    file: "kitchen_after.JPG"
    #title: "Kitchen after"
    effect: kenburns-zoom-out
    duration: 10

  - id: bath_before
    file: "bath_before.JPG"
    #title: "Bath before "
    effect: kenburns-zoom-in
    duration: 10

  - id: bath_during
    file: "bath_during/*.JPG"
    #title: "Bath during ..."
    effect: fade
    duration: 3

  - id: kitchen_animation
    file: "kitchen_during/*.JPG"     # glob pattern expands to multiple frames
    title: "Kitchen Time-Lapse"
    effect: animate-smooth           # smooth transition between frames
    #duration: 8                      # total time (seconds)
    fps: 3                          # frame rate (frames per second)    
    repeat: 3

  - id: bath_after
    file: "bath_after.JPG"
    #title: "Bath after ..."
    effect: kenburns-zoom-out
    duration: 10

  - id: powder_before
    file: "powder_before.JPG"
    #title: "Powder room before "
    effect: kenburns-zoom-in
    duration: 10

  - id: powder_during
    file: "powder_during/*.JPG"
    #title: "Powder room during ..."
    effect: fade
    duration: 3

  - id: powder_after
    file: "powder_after.JPG"
    #title: "Powder room after ..."
    effect: kenburns-zoom-out
    duration: 10

  - id: pause_2
    file: ""
    title: ""
    effect: none
    duration: 2    

  - id: pause_10
    file: ""
    title: ""
    effect: none
    duration: 10

  - id: weather_widget
    type: html
    url: "/pages/weather.html"
    title: "Richmond Weather"
    duration: 10

  - id: james_river_water_level
    type: html
    url: "https://water.noaa.gov/gauges/rmdv2"
    title: 
    duration: 10

  - id: river_center_video
    type: youtube
    video_id: "erBoOFKTH4E"
    duration: 10
    title: "JRA’s Jim Buzzard River Education Center"


#https://youtu.be/erBoOFKTH4E


# --- Default playlist shared by all kiosks ---
default:
  include: [kitchen_before, kitchen_during, bath_during, bath_after ]

# --- Client-specific playlists (subsets or overrides) ---

clients:
  Scrollsaw:
    #include: [kitchen_before, kitchen_during, kitchen_after, pause_2, kitchen_animation, pause_2, powder_before, powder_during, powder_after, pause_2, bath_before, bath_during, bath_after, pause_2 ]
    include: [kitchen_before, kitchen_during, kitchen_after, pause_2, powder_before, powder_during, powder_after, pause_2, bath_before, bath_during, bath_after, pause_2 ]

  kiosk1.local:
    include: [kitchen_before, kitchen_during, bath_during, bath_after ]

  pi4office:
    include: [kitchen_before, kitchen_during, kitchen_after, pause_2, powder_before, powder_during, powder_after, pause_2, bath_before, bath_during, bath_after, pause_2 ]

  EGR-JL-DSK0-SRV:
    include: [river_center_video, kitchen_before, james_river_water_level, weather_widget, kitchen_animation, kitchen_after, pause_2]
