# config.yaml
slides:
  # --- Master library of reusable slides ---
  - id: kitchen_before
    file: "kitchen_before.JPG"
    #title: "Kitchen before"
    effect: kenburns-zoom-in
    duration: 10

  - id: kitchen_during
    file: "kitchen_during/*.JPG"
    #title: "Kitchen during ..."
    effect: cut
    duration: 3

  - id: kitchen_after
    file: "kitchen_after.JPG"
    #title: "Kitchen after"
    effect: kenburns-zoom-out
    duration: 10

  - id: bath_before
    file: "bath_before.JPG"
    #title: "Bath before "
    effect: kenburns-zoom-in
    duration: 10

  - id: bath_during
    file: "bath_during/*.JPG"
    #title: "Bath during ..."
    effect: fade
    duration: 3

  - id: kitchen_animation
    file: "kitchen_during/*.JPG"     # glob pattern expands to multiple frames
    title: "Kitchen Time-Lapse"
    effect: animate-smooth           # smooth transition between frames
    #duration: 8                      # total time (seconds)
    fps: 3                          # frame rate (frames per second)    
    repeat: 3

  - id: bath_after
    file: "bath_after.JPG"
    #title: "Bath after ..."
    effect: kenburns-zoom-out
    duration: 10

  - id: powder_before
    file: "powder_before.JPG"
    #title: "Powder room before "
    effect: kenburns-zoom-in
    duration: 10

  - id: powder_during
    file: "powder_during/*.JPG"
    #title: "Powder room during ..."
    effect: fade
    duration: 3

  - id: powder_after
    file: "powder_after.JPG"
    #title: "Powder room after ..."
    effect: kenburns-zoom-out
    duration: 10

  - id: pause_2
    file: ""
    title: ""
    effect: none
    duration: 2    

  - id: pause_1
    duration: 1


  - id: pause_10
    file: ""
    title: ""
    effect: none
    duration: 10


  - id: weather_dashboard
    type: html
    url: "/pages/weather.html"
    duration: 15


  - id: james_river_water_level
    type: html
    url: "https://water.noaa.gov/gauges/rmdv2"
    title: 
    duration: 10

  - id: river_center_live_video
    type: youtube
    video_id: "erBoOFKTH4E"
    duration: 15
    title: "JRA’s Jim Buzzard River Education Center"


  - id: james_river_flyover
    type: youtube
    video_id: "ufX8tv6P6Wg"
    duration: 180
    title: "Drone footage over the James River"


  - id: house_mux_2x2
    type: mux
    layout: 2x2
    duration: infinite
    title: "Home Renovation Overview"
    hide_panel_titles: true
    panels:
      - slides: [james_river_flyover]
        panel_duration: 180
      - slides: [bath_before, bath_during, bath_after, pause_1 ]
        #panel_duration: 4
      - slides: [ kitchen_before, kitchen_during, kitchen_after, pause_1]
        #panel_duration: 6
      - slides: [ weather_dashboard,river_center_live_video]  # empty
        #panel_duration: infinite

  - id: house_mux_test
    type: mux
    layout: 1x2
    duration: infinite
    #title: "Home Renovation Overview"
    hide_panel_titles: true
    panels:
      - slides: [bath_before, bath_during, bath_after, pause_1 ]
        align: "center bottom"
      - slides: [ powder_before, powder_during, powder_after, pause_2]
        align: "center top"


#https://youtu.be/erBoOFKTH4E


# --- Default playlist shared by all kiosks ---
default:
  include: [kitchen_before, kitchen_during, bath_during, bath_after ]

# --- Client-specific playlists (subsets or overrides) ---

clients:
  Scrollsaw:
    #include: [kitchen_before, kitchen_during, kitchen_after, pause_2, kitchen_animation, pause_2, powder_before, powder_during, powder_after, pause_2, bath_before, bath_during, bath_after, pause_2 ]
    #include: [kitchen_before, kitchen_during, kitchen_after, pause_2, powder_before, powder_during, powder_after, pause_2, bath_before, bath_during, bath_after, pause_2 ]
    #include: [river_center_live_video, james_river_flyover]
    include: [ house_mux_2x2 ]
    #include: [powder_before, powder_during, powder_after, pause_2]
    #include: [bath_before,bath_during,bath_after,pause_1]
    #include: [kitchen_before, kitchen_during, kitchen_after, pause_1 ]
    #include: [weather_dashboard, river_center_live_video]

  kiosk1.local:
    include: [kitchen_before, kitchen_during, bath_during, bath_after ]

  pi4office:
    include: [kitchen_before, kitchen_during, kitchen_after, pause_2, powder_before, powder_during, powder_after, pause_2, bath_before, bath_during, bath_after, pause_2 ]

  EGR-JL-DSK0-SRV:
    #include: [river_center_video, kitchen_before, james_river_water_level, weather_widget, kitchen_animation, kitchen_after, pause_2]
    include: [ house_mux_2x2 ]
