# config.yaml
slides:
  # --- Master library of reusable slides ---
  - id: kitchen_before
    file: "055A2853.JPG"
    title: "Kitchen before"
    effect: kenburns-zoom-in
    duration: 6

  - id: kitchen_during
    file: "2025-06-02_20-21-21EOS R3_4464.JPG"
    title: "Kitchen during ..."
    effect: kenburns-zoom-out
    duration: 5

  - id: bath_during
    file: "055A2876.JPG"
    title: "Bath during ..."
    effect: kenburns-pan-left
    duration: 7

  - id: bath_after
    file: "2025-08-15_17-12-05EOS R3_4754.JPG"
    title: "Bath after ..."
    effect: kenburns-pan-right
    duration: 5

  - id: pause_2
    file: ""
    title: ""
    effect: none
    duration: 2    

  - id: pause_10
    file: ""
    title: ""
    effect: none
    duration: 10   


# --- Default playlist shared by all kiosks ---
default:
  include: [kitchen_before, kitchen_during, bath_during, bath_after ]

# --- Client-specific playlists (subsets or overrides) ---

clients:
  Scrollsaw:
    include: [kitchen_before, kitchen_during, pause_2, bath_during, bath_after, pause_10 ]

  kiosk1.local:
    include: [kitchen_before, kitchen_during, bath_during, bath_after ]
