services:
  photo-kiosk:
    image: ssg-kiosk-photo-player:latest   # 👈 add this line
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-kiosk
    hostname: ${HOSTNAME:-${HOST:-${COMPUTERNAME:-default-client}}}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./photos:/app/photos
      - ./public:/app/public
      - ./logs:/app/logs   # ✅ persist logs to host
    environment:
      - NODE_ENV=production
      # 🔹 portable fallback chain
      - CLIENT_ID=${HOSTNAME:-${HOST:-${COMPUTERNAME:-default-client}}}
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    profiles: [production]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
      