version: "3.9"

services:
  photo-kiosk:
    image: your-dockerhub-username/ssg-kiosk-photo-player:latest
    container_name: photo-kiosk
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./photos:/app/photos
      - ./public:/app/public
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true         # remove old images
      - WATCHTOWER_POLL_INTERVAL=3600   # check every hour
      - WATCHTOWER_LABEL_ENABLE=true    # optional fine-grained control
